### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by beverlyguillermo** [scoutforpets/ember-fullcalendar#43]
ember-fullcalendar `1.5.0` with ember-cli `2.12.0`

New deprecation warning caused by 2.12.0 changes
```
DEPRECATION: Using "_lookupFactory" is deprecated. Please use container.factoryFor instead. [deprecation id: container-lookupFactory] See http://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor for more details.
        at logDeprecationStackTrace (http://localhost:3000/2/assets/vendor.js:21854:19)
        at HANDLERS.(anonymous function) (http://localhost:3000/2/assets/vendor.js:21965:7)
        at raiseOnDeprecation (http://localhost:3000/2/assets/vendor.js:21884:12)
        at HANDLERS.(anonymous function) (http://localhost:3000/2/assets/vendor.js:21965:7)
        at invoke (http://localhost:3000/2/assets/vendor.js:21981:7)
        at deprecate (http://localhost:3000/2/assets/vendor.js:21949:32)
        at Object.deprecate (http://localhost:3000/2/assets/vendor.js:33791:37)
        at Container.lookupFactory (http://localhost:3000/2/assets/vendor.js:17370:19)
        at Class._lookupFactory (http://localhost:3000/2/assets/vendor.js:49064:33)
```

When I just did the quick change to use the container.factoryFor on https://github.com/scoutforpets/ember-fullcalendar/blob/master/addon/components/full-calendar.js#L24, I got the following error.

```
Error: You attempted to access "emberFullCalendar" on a factory manager created by container#factoryFor. "emberFullCalendar" is not a member of a factory manager."
    at Object.get (vendor.js:17430)
    at Class.<anonymous> (vendor.js:130034)
    at ComputedPropertyPrototype.get (vendor.js:33431)
    at Object.get (vendor.js:38424)
    at Class.get (vendor.js:51162)
    at Class.didInsertElement (vendor.js:130130)
    at Class.trigger (vendor.js:58863)
    at Class.superWrapper [as trigger] (vendor.js:56914)
    at CurlyComponentManager.didCreate (vendor.js:29083)
    at Environment.commit (vendor.js:67533)
defaultDispatch @ vendor.js:34050
```

**Comment by jamesdixon** [comment]
fixed via 5685a3

thanks!
