### ISSUE TITLE
can't build for production

### ISSUE THREAD

**Issue by yandiro** [scoutforpets/ember-fullcalendar#89]
Could not build the ember app for production with `npm run build` with ember-fullcalendar installed.

Here is the log:

`=================================================================================

ENV Summary:

  TIME: Tue Jan 11 2022 12:00:20 GMT+1030 (Australian Central Daylight Time)
  TITLE: ember
  ARGV:
  - /usr/bin/node
  - /home/username/git/myapp/myapp-app/client/myapp-app/node_modules/.bin/ember
  - build
  - --environment=production
  EXEC_PATH: /usr/bin/node
  TMPDIR: /tmp
  SHELL: /usr/bin/zsh
  PATH:
  - /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /home/username/git/myapp/myapp-app/client/myapp-app/node_modules/.bin
  - /usr/local/bin
  - /usr/local/sbin
  - /usr/bin
  - /usr/sbin
  - /home/username/bin
  - /home/username/bin
  PLATFORM: linux x64
  FREEMEM: 8806834176
  TOTALMEM: 20792758272
  UPTIME: 2084.84
  LOADAVG: 1.13,1.29,1.38
  CPUS:
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 3913
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 4000
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 3932
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz - 2400
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.18.1
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.4
  - modules: 83
  - napi: 8
  - nghttp2: 1.46.0
  - node: 14.18.2
  - openssl: 1.1.1l
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.42.0
  - v8: 8.4.371.23-node.85
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: Unexpected token: eof (undefined)
    at js_error (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:548:11)
    at croak (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1272:9)
    at token_error (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1280:9)
    at unexpected (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1286:9)
    at block_ (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:2169:28)
    at statement (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1401:29)
    at _embed_tokens_wrapper (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1337:26)
    at if_ (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:2153:44)
    at statement (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1471:24)
    at _embed_tokens_wrapper (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1337:26)
  - code: [undefined]
  - codeFrame: Unexpected token: eof (undefined)
  - errorMessage: Unexpected token: eof (undefined)
        at TerserWriter
-~- created here: -~-
    at new Plugin (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new TerserWriter (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/index.js:30:5)
    at Class.postprocessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli-terser/index.js:61:14)
    at /home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/broccoli/ember-app.js:842:12)
    at EmberApp.host.addonPostprocessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-auto-import/js/auto-import.js:103:20)
    at EmberApp.toTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1665:17)
    at EmberApp.appInstance.toTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-validators/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: 142833
    - treeDir: [undefined]
  - message: Unexpected token: eof (undefined)
        at TerserWriter
-~- created here: -~-
    at new Plugin (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new TerserWriter (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/index.js:30:5)
    at Class.postprocessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli-terser/index.js:61:14)
    at /home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/broccoli/ember-app.js:842:12)
    at EmberApp.host.addonPostprocessTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-auto-import/js/auto-import.js:103:20)
    at EmberApp.toTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-cli/lib/broccoli/ember-app.js:1665:17)
    at EmberApp.appInstance.toTree (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/ember-validators/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: TerserWriter
  - originalErrorMessage: Unexpected token: eof (undefined)
  - stack: SyntaxError: Unexpected token: eof (undefined)
    at js_error (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:548:11)
    at croak (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1272:9)
    at token_error (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1280:9)
    at unexpected (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1286:9)
    at block_ (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:2169:28)
    at statement (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1401:29)
    at _embed_tokens_wrapper (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1337:26)
    at if_ (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:2153:44)
    at statement (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1471:24)
    at _embed_tokens_wrapper (/home/username/git/myapp/myapp-app/client/myapp-app/node_modules/broccoli-terser-sourcemap/node_modules/terser/dist/bundle.min.js:1337:26)

=================================================================================
`

**Comment by rana-nouman** [comment]
@yandiro  Issue is related to ember-cli-moment-shim package. If this upgraded to v3.8.0, then issue will be resolved !
